# -*- coding: utf-8 -*-
"""subtitles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jwUB6JJUClsRDu594vP4yz-2zF-LhG7D
"""

# 📦 Install dependencies
!pip install -q git+https://github.com/openai/whisper.git
!pip install -q ffmpeg-python
!sudo apt-get install -y ffmpeg

# 📤 Upload video file dynamically
from google.colab import files
uploaded = files.upload()

import os
uploaded_filename = next(iter(uploaded))  # get the uploaded file name
print(f"Uploaded file: {uploaded_filename}")

# 📚 Import libraries
import whisper
import ffmpeg
from datetime import timedelta

# 📌 Load Whisper large-v3 model
model = whisper.load_model("large-v3")

def transcribe_audio(video_path, output_srt_path):
    print(f"Transcribing: {video_path}")
    result = model.transcribe(video_path, task="translate")
    segments = result["segments"]

    with open(output_srt_path, "w", encoding="utf-8") as srt_file:
        for i, segment in enumerate(segments, start=1):
            srt_file.write(f"{i}\n")
            srt_file.write(f"{format_timestamp(segment['start'])} --> {format_timestamp(segment['end'])}\n")
            srt_file.write(segment["text"].strip() + "\n\n")

    print(f"SRT subtitles saved to: {output_srt_path}")

def format_timestamp(seconds):
    millisec = int((seconds - int(seconds)) * 1000)
    time = str(timedelta(seconds=int(seconds)))
    if len(time.split(":")[0]) < 2:
        time = "0" + time
    return f"{time},{millisec:03d}"

def burn_subtitles(video_path, srt_path, output_path):
    try:
        print(f"Burning subtitles into: {output_path}")
        ffmpeg.input(video_path).output(output_path, vf=f"subtitles='{srt_path}'").run(overwrite_output=True)
        print(f"Subtitled video saved to: {output_path}")
    except ffmpeg.Error as e:
        print(f"FFmpeg Error: {e.stderr.decode()}")
        raise

def main():
    video_path = f"/content/{uploaded_filename}"
    srt_output_path = "/content/output_subs.srt"
    subtitled_video_path = "/content/final_output.mp4"

    transcribe_audio(video_path, srt_output_path)
    burn_subtitles(video_path, srt_output_path, subtitled_video_path)

    print("✅ All done. Download your files below:")

# 🎬 Run the process
main()

# 📥 Download final video and subtitles
from google.colab import files
files.download("/content/final_output.mp4")
files.download("/content/output_subs.srt")